#!/usr/bin/env python3
"""
将 Egern YAML 格式规则集转换为 Surge/Loon 兼容的两段式 .list 格式。
支持字段: domain_set -> DOMAIN, domain_suffix_set -> DOMAIN-SUFFIX,
          domain_keyword_set -> DOMAIN-KEYWORD
用法: python3 convert_to_surge.py <input.yaml> <output.list>
"""
import sys
import yaml

FIELD_MAP = {
    "domain_set": "DOMAIN",
    "domain_suffix_set": "DOMAIN-SUFFIX",
    "domain_keyword_set": "DOMAIN-KEYWORD",
}

def convert(input_path, output_path):
    with open(input_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    lines = []
    lines.append(f"# Auto-converted from {input_path.split('/')[-1]} — DO NOT EDIT DIRECTLY")
    lines.append("# Source of truth is the Egern YAML file; this file is regenerated by GitHub Actions")
    lines.append("")

    for field, prefix in FIELD_MAP.items():
        values = data.get(field) or []
        for v in values:
            lines.append(f"{prefix},{v}")

    unsupported = [k for k in data.keys() if k not in FIELD_MAP and k != "no_resolve"]
    if unsupported:
        lines.append("")
        lines.append(f"# NOTE: source YAML also contains unsupported fields for Loon: {', '.join(unsupported)}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Converted {input_path} -> {output_path} ({sum(len(data.get(k) or []) for k in FIELD_MAP)} rules)")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 convert_to_surge.py <input.yaml> <output.list>")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
